[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  name = "github.com/goph/logur"
  version = "0.9.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/goph/emperror"
  version = "0.16.0"

[[override]]
  name = "github.com/InVisionApp/go-logger"
  version = "1.0.1"

[[constraint]]
  name = "github.com/InVisionApp/go-health"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/cloudflare/tableflip"

[[constraint]]
  name = "github.com/oklog/run"
  version = "1.0.0"

[[constraint]]
  name = "go.opencensus.io"
  version = "0.18.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "github.com/opencensus-integrations/ocsql"
  version = "0.1.3"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "2.0.0"

[[constraint]]
  name = "github.com/ThreeDotsLabs/watermill"
  version = "0.2.1"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.2.0"

[[constraint]]
  name = "github.com/mccutchen/go-httpbin"
  version = "1.1.1"
