{{- if .Values.application.ingress.enabled -}}
{{- $fullName := include "spotguide-modern-go-application.fullname" . -}}
{{- $ingressPath := .Values.application.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "spotguide-modern-go-application.name" . }}
    helm.sh/chart: {{ include "spotguide-modern-go-application.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: {{ include "spotguide-modern-go-application.name" . }}
{{- with .Values.application.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.application.ingress.tls }}
  tls:
  {{- range .Values.application.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.application.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: app
  {{- end }}
{{- end }}
